### PR TITLE
Modernize plugin

### PR DESCRIPTION
**Pull request by jhillyerd**
Update plugin-proxy to resemble current Oh My Fish plugins

### CODE REVIEW

**Comment by jhillyerd** [comment]
@bobthecow - does this look about right for a modern plugin?

**Comment by derekstavis** [comment]
:+1: I like the changes. The only detail is that you could remove `uninstall.fish` and `completions/` as they are not being used right now.

**Comment by jhillyerd** [comment]
Would it make sense to add:

```
functions -e proxy noproxy
```

to the uninstall code?

**Comment by derekstavis** [comment]
Yes. Also `set -e` any variable set with `set -x` and `set -g`.

**Pull request merged**
